### PR TITLE
Update arcgis

### PR DESCRIPTION
**Pull request by clechot**

### CODE REVIEW

**Review by mistafunk — CHANGES_REQUESTED** [review]
Basically fine:
* Please try once more to get rid of the accidental line endings changes
* Some of the requirements files entries are now "unversioned", which means the required environment is not completely defined anymore. Was there now resolvable combination of packages?

**Comment by clechot** [comment]
Concerning the unversioned packages, as those packages are dependencies (or even dependencies of dependencies), I thought that that would be a problem to remove the version. Do you prefer having all the packages versioned in the environment files?

**Review by mistafunk — CHANGES_REQUESTED** [review]
I've added a commit with updated pip reqs for Linux.

Please re-freeze the pip reqs files for Windows as well (so we have pinned versions everywhere).

**Review by mistafunk — APPROVED** [review]
LGTM

**Pull request merged**
